import React, { useState } from 'react';
import { X, KeyRound, Info, CheckCircle2 } from 'lucide-react';
import { Button } from '@/Components/Button';

interface JoinProjectModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export function JoinProjectModal({ isOpen, onClose }: JoinProjectModalProps) {
    const [code, setCode] = useState('');
    const [isSubmitted, setIsSubmitted] = useState(false);

    if (!isOpen) return null;

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!code.trim()) return;
        setIsSubmitted(true);
    };

    const handleClose = () => {
        setCode('');
        setIsSubmitted(false);
        onClose();
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs">
            <div
                className="w-full max-w-md bg-[var(--card)] border border-[var(--border)] rounded-2xl shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Header */}
                <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--border)]">
                    <div className="flex items-center gap-2.5">
                        <div className="w-8 h-8 rounded-xl bg-[var(--tint-orange)] flex items-center justify-center text-[#EC7505]">
                            <KeyRound className="w-4 h-4" />
                        </div>
                        <div>
                            <h3 className="text-base font-bold text-[var(--ink)]">
                                Join With a Code
                            </h3>
                            <p className="text-xs text-[var(--muted)]">
                                Enter your project or committee invite code
                            </p>
                        </div>
                    </div>
                    <button
                        type="button"
                        onClick={handleClose}
                        className="p-1 rounded-lg text-[var(--muted)] hover:text-[var(--ink)] hover:bg-[var(--tint-neutral)]"
                    >
                        <X className="w-4 h-4" />
                    </button>
                </div>

                {/* Content */}
                <div className="p-6">
                    {isSubmitted ? (
                        <div className="text-center py-4 space-y-3">
                            <CheckCircle2 className="w-10 h-10 text-[#FFBB00] mx-auto" />
                            <h4 className="text-sm font-bold text-[var(--ink)]">
                                Invitation Code Submitted
                            </h4>
                            <p className="text-xs text-[var(--muted)] leading-relaxed">
                                Your membership request for code <strong className="text-[var(--ink)] font-mono">{code}</strong> has been sent to the Project Leader for committee approval.
                            </p>
                            <div className="pt-2">
                                <Button variant="primary" size="sm" onClick={handleClose}>
                                    Got it
                                </Button>
                            </div>
                        </div>
                    ) : (
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div>
                                <label className="block text-xs font-bold text-[var(--ink)] mb-1">
                                    Invitation Code
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={code}
                                    onChange={(e) => setCode(e.target.value.toUpperCase())}
                                    placeholder="e.g. CCIS-PROJ-891"
                                    className="w-full px-3.5 py-2.5 text-sm font-mono tracking-wider uppercase rounded-xl border border-[var(--border)] bg-[var(--card)] text-[var(--ink)] placeholder-[var(--muted)] outline-none focus:border-[#EC7505]"
                                />
                            </div>

                            <div className="flex items-start gap-2.5 p-3 rounded-xl bg-[var(--tint-neutral)] text-xs text-[var(--muted)]">
                                <Info className="w-4 h-4 text-[var(--link-orange)] shrink-0 mt-0.5" />
                                <p className="leading-snug">
                                    Project codes are generated by faculty project leaders and committee staff for class or capstone groups.
                                </p>
                            </div>

                            <div className="pt-2 flex items-center justify-end gap-3 border-t border-[var(--border)]">
                                <Button type="button" variant="secondary" size="md" onClick={handleClose}>
                                    Cancel
                                </Button>
                                <Button type="submit" variant="primary" size="md">
                                    Join project
                                </Button>
                            </div>
                        </form>
                    )}
                </div>
            </div>
        </div>
    );
}
